### ISSUE TITLE
resolve issue with cmyk transparency

### ISSUE THREAD

**Issue by carlos-dubon** [carlos-dubon/chroma#8]
i think this color mode should be removed bc there isn't an opacity mode for it

**Comment by Angel-Ponce** [comment]
In this case, for popularity we should remove cmyk and hsl color modes.

**Comment by carlos-dubon** [comment]
Aight then. Cmyk and hsl will get removed.

**Comment by carlos-dubon** [comment]
cmyk and hsl color modes removed
